name: Check SUSFS Updates

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  check-updates:
    runs-on: ubuntu-latest
    outputs:
      should_trigger: ${{ steps.check.outputs.should_trigger }}

    steps:
    - name: Get latest commit hash from SUSFS
      id: check
      run: |
        SUSFS_REPO="https://github.com/ShirkNeko/susfs4ksu.git"
        SUSFS_BRANCH="gki-android13-5.15"

        git clone --quiet --depth 1 -b "$SUSFS_BRANCH" "$SUSFS_REPO" susfs-check
        cd susfs-check
        COMMIT_HASH=$(git rev-parse HEAD)
        echo "Latest SUSFS commit: $COMMIT_HASH"

        # Save hash for comparison
        mkdir -p ../.cache
        HASH_FILE="../.cache/susfs-last-hash.txt"

        if [ -f "$HASH_FILE" ]; then
          OLD_HASH=$(cat "$HASH_FILE")
        else
          OLD_HASH=""
        fi

        if [ "$COMMIT_HASH" != "$OLD_HASH" ]; then
          echo "New commit detected: $COMMIT_HASH"
          echo "$COMMIT_HASH" > "$HASH_FILE"
          echo "should_trigger=true" >> $GITHUB_OUTPUT
        else
          echo "No new commits."
          echo "should_trigger=false" >> $GITHUB_OUTPUT
        fi

    - name: Trigger patch generation if needed
      if: steps.check.outputs.should_trigger == 'true'
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
          -d '{"ref":"main"}'
