name: Generate SUSFS Patches

on:
  workflow_run:
    workflows: ["Check SUSFS Updates"]
    types:
      - completed
  workflow_dispatch:

jobs:
  generate-patches:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch_config:
          - { susfs_branch: 'gki-android12-5.10', kernel_branch: 'android12-5.10-lts', kernel_version: '5.10', android_version: '12' }
          - { susfs_branch: 'gki-android13-5.10', kernel_branch: 'android13-5.10-lts', kernel_version: '5.10', android_version: '13' }
          - { susfs_branch: 'gki-android13-5.15', kernel_branch: 'android13-5.15-lts', kernel_version: '5.15', android_version: '13' }
          - { susfs_branch: 'gki-android14-5.15', kernel_branch: 'android14-5.15-lts', kernel_version: '5.15', android_version: '14' }
          - { susfs_branch: 'gki-android14-6.1', kernel_branch: 'android14-6.1-lts', kernel_version: '6.1', android_version: '14' }
          - { susfs_branch: 'gki-android15-6.6', kernel_branch: 'android15-6.6-lts', kernel_version: '6.6', android_version: '15' }
    name: Generate SUSFS Patches for Android ${{ matrix.branch_config.android_version }} (Kernel ${{ matrix.branch_config.kernel_version }})

    steps:
    - name: Set up Git identity
      run: |
        git config --global user.name "belowzeroiq"
        git config --global user.email "belowzeroiq@proton.me"

    - name: Clone SUSFS source
      run: |
        git clone \
          --depth 1 \
          -b "${{ matrix.branch_config.susfs_branch }}" \
          "https://github.com/ShirkNeko/susfs4ksu.git" \
          susfs-source
            
    - name: Extract SUSFS version and commit hash
      id: set_tag
      run: |
        SUSFS_VERSION=$(grep -oP '#define SUSFS_VERSION "\K[^"]+' susfs-source/kernel_patches/include/linux/susfs.h)
        SUSFS_COMMIT_HASH=$(git -C susfs-source rev-parse --short HEAD)
        TAG_NAME="${SUSFS_VERSION}-${SUSFS_COMMIT_HASH}-android${{ matrix.branch_config.android_version }}-${{ matrix.branch_config.kernel_version }}"
        echo "SUSFS_VERSION=${SUSFS_VERSION}" >> $GITHUB_OUTPUT
        echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT

    - name: Clone kernel source
      run: |
        git clone \
          --depth 1 \
          -b "${{ matrix.branch_config.kernel_branch }}" \
          "https://android.googlesource.com/kernel/common" \
          kernel-source

    - name: Generate patches (exclude KernelSU only)
      run: |
        cd kernel-source
        git checkout -b susfs-patched

        # Copy everything EXCEPT KernelSU/
        if [ -d "../susfs-source/kernel_patches" ]; then
          rsync -av --exclude='KernelSU/' ../susfs-source/kernel_patches/ .
        fi

        # Apply the additional patch
        PATCH_FILE="../susfs-source/kernel_patches/50_add_susfs_in_${{ matrix.branch_config.susfs_branch }}.patch"
        if [ -f "$PATCH_FILE" ]; then
          echo "Applying patch..."
          git apply --whitespace=fix "$PATCH_FILE"
        else
          echo "Patch file not found: $PATCH_FILE"
          exit 1
        fi

        # Generate patches
        git add -A
        if ! git diff --staged --quiet; then
          git commit -m "Implement SUSFS ${{ steps.set_tag.outputs.SUSFS_VERSION }} for Android ${{ matrix.branch_config.android_version }} (Kernel ${{ matrix.branch_config.kernel_version }})"
          mkdir -p ../generated-patches
          git format-patch "${{ matrix.branch_config.kernel_branch }}" --output-directory ../generated-patches/
        else
          echo "No changes detected!"
          exit 1
        fi

    - name: Create release with .patch files
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.set_tag.outputs.tag_name }}
        name: "SUSFS Patches for Android ${{ matrix.branch_config.android_version }} (Kernel ${{ matrix.branch_config.kernel_version }})"
        body: |
          **Generated from:**
          - SUSFS: `ShirkNeko/susfs4ksu@${{ matrix.branch_config.susfs_branch }}`
          - Kernel: `android/common@${{ matrix.branch_config.kernel_branch }}`

          **Android Version:** ${{ matrix.branch_config.android_version }}
          **Kernel Version:** ${{ matrix.branch_config.kernel_version }}

          **Includes:**
          - `fs/` modifications
          - `include/` headers

          **Apply with:**
          ```sh
          git apply *.patch
          ```
        files: |
          generated-patches/*.patch
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}