name: Generate SUSFS Patches

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      susfs_repo:
        description: 'SUSFS repository'
        required: true
        default: 'ShirkNeko/susfs4ksu'
      susfs_branch:
        description: 'SUSFS branch to track'
        required: true
        default: 'gki-android13-5.15'
      kernel_repo:
        description: 'Kernel repository'
        required: true
        default: 'topnotchfreaks/kernel_msm-5.15'
      kernel_branch:
        description: 'Kernel branch'
        required: true
        default: 'google'

jobs:
  generate-patches:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git identity
      run: |
        git config --global user.name "belowzeroiq"
        git config --global user.email "belowzeroiq@proton.me"

    - name: Clone SUSFS source
      run: |
        git clone \
          --depth 1 \
          -b "${{ github.event.inputs.susfs_branch || 'gki-android13-5.15' }}" \
          "https://github.com/${{ github.event.inputs.susfs_repo || 'ShirkNeko/susfs4ksu' }}.git" \
          susfs-source

    - name: Clone kernel source
      run: |
        git clone \
          --depth 50 \
          -b "${{ github.event.inputs.kernel_branch || 'google' }}" \
          "https://github.com/${{ github.event.inputs.kernel_repo || 'topnotchfreaks/kernel_msm-5.15' }}.git" \
          kernel-source

    - name: Generate patches (exclude KernelSU only)
      run: |
        cd kernel-source
        git checkout -b susfs-patched

        # Copy everything EXCEPT KernelSU/
        if [ -d "../susfs-source/kernel_patches" ]; then
          rsync -av --exclude='KernelSU/' ../susfs-source/kernel_patches/ .
        fi

        # Generate patches
        git add -A
        if ! git diff --staged --quiet; then
          git commit -m "Apply SUSFS changes (excl. KernelSU)"
          mkdir -p ../generated-patches
          git format-patch "${{ github.event.inputs.kernel_branch || 'google' }}" --output-directory ../generated-patches/
          git diff "${{ github.event.inputs.kernel_branch || 'google' }}" > ../generated-patches/susfs-combined.patch
        else
          echo "No changes detected!"
          exit 1
        fi

    - name: Create release with .patch files
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "susfs-patches-$(date +%Y%m%d)"
        name: "SUSFS Patches ($(date +'%Y-%m-%d'))"
        body: |
          **Generated from:**
          - SUSFS: `${{ github.event.inputs.susfs_repo || 'ShirkNeko/susfs4ksu' }}@${{ github.event.inputs.susfs_branch || 'gki-android13-5.15' }}`
          - Kernel: `${{ github.event.inputs.kernel_repo || 'topnotchfreaks/kernel_msm-5.15' }}@${{ github.event.inputs.kernel_branch || 'google' }}`

          **Includes:**
          - `fs/` modifications
          - `include/` headers
          - **Excludes:** `KernelSU/` folder

          **Apply with:**
          ```sh
          git am *.patch  # For split patches
          # OR
          git apply susfs-combined.patch  # For combined diff
          ```
        files: |
          generated-patches/*.patch
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}