name: Generate SUSFS Patches

on:
  workflow_run:
    workflows: ["Check SUSFS Updates"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      susfs_repo:
        description: 'SUSFS repository'
        required: true
        default: 'ShirkNeko/susfs4ksu'
      susfs_branch:
        description: 'SUSFS branch to track'
        required: true
        default: 'gki-android13-5.15'
      kernel_repo:
        description: 'Kernel repository'
        required: true
        default: 'topnotchfreaks/kernel_msm-5.15'
      kernel_branch:
        description: 'Kernel branch'
        required: true
        default: 'google'

jobs:
  generate-patches:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git identity
      run: |
        git config --global user.name "belowzeroiq"
        git config --global user.email "belowzeroiq@proton.me"

    - name: Clone SUSFS source
      run: |
        git clone \
          --depth 1 \
          -b "${{ github.event.inputs.susfs_branch || 'gki-android13-5.15' }}" \
          "https://github.com/${{ github.event.inputs.susfs_repo || 'ShirkNeko/susfs4ksu' }}.git" \
          susfs-source
            
    - name: Extract SUSFS version and commit hash
      id: set_tag
      run: |
        SUSFS_VERSION=$(grep -oP '#define SUSFS_VERSION "\K[^"]+' susfs-source/kernel_patches/include/linux/susfs.h)
        SUSFS_COMMIT_HASH=$(git -C susfs-source rev-parse --short HEAD)
        TAG_NAME="${SUSFS_VERSION}-${SUSFS_COMMIT_HASH}"
        echo "SUSFS_VERSION=${SUSFS_VERSION}" >> $GITHUB_OUTPUT
        echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT

    - name: Clone kernel source
      run: |
        git clone \
          --depth 50 \
          -b "${{ github.event.inputs.kernel_branch || 'google' }}" \
          "https://github.com/${{ github.event.inputs.kernel_repo || 'topnotchfreaks/kernel_msm-5.15' }}.git" \
          kernel-source

    - name: Generate patches (exclude KernelSU only)
      run: |
        cd kernel-source
        git checkout -b susfs-patched

        # Copy everything EXCEPT KernelSU/
        if [ -d "../susfs-source/kernel_patches" ]; then
          rsync -av --exclude='KernelSU/' ../susfs-source/kernel_patches/ .
        fi

        # Apply the additional patch
        if [ -f "../susfs-source/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch" ]; then
          echo "Applying 50_add_susfs_in_gki-android13-5.15.patch..."
          git apply --whitespace=fix ../susfs-source/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch
        else
          echo "Patch file not found!"
          exit 1
        fi

        # Generate patches
        git add -A
        if ! git diff --staged --quiet; then
          git commit -m "Implement SUSFS ${{ steps.set_tag.outputs.SUSFS_VERSION }}"
          mkdir -p ../generated-patches
          git format-patch "${{ github.event.inputs.kernel_branch || 'google' }}" --output-directory ../generated-patches/
        else
          echo "No changes detected!"
          exit 1
        fi

    - name: Create release with .patch files
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.set_tag.outputs.tag_name }}
        name: "SUSFS Patches (${{ steps.set_tag.outputs.tag_name }})"
        body: |
          **Generated from:**
          - SUSFS: `${{ github.event.inputs.susfs_repo || 'ShirkNeko/susfs4ksu' }}@${{ github.event.inputs.susfs_branch || 'gki-android13-5.15' }}`
          - Kernel: `${{ github.event.inputs.kernel_repo || 'topnotchfreaks/kernel_msm-5.15' }}@${{ github.event.inputs.kernel_branch || 'google' }}`

          **Includes:**
          - `fs/` modifications
          - `include/` headers

          **Apply with:**
          ```sh
          git apply *.patch
          ```
        files: |
          generated-patches/*.patch
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}